name: URL Content Monitor and Release

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      force_release:
        description: '强制创建release'
        required: false
        default: 'false'






env:
  # 设置要监控的三个URL
  URL_1: "http://www.zmyxl2016.com/urls.txt"
  URL_2: "http://www.zmyxl2008.com/cpm.txt" 
  URL_3: "http://www.jfglzs.com/software/jfgl2.zip"



jobs:
  monitor-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Generate unique tag
      id: tag
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        TAG="release-${TIMESTAMP}-${GITHUB_RUN_ID}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo "name=自动发布-${TIMESTAMP}" >> $GITHUB_OUTPUT
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
        
    - name: Download and compare content
      id: monitor
      run: |
        python .github/scripts/url_monitor.py
        
    - name: Download changed files
      if: steps.monitor.outputs.changed == 'true' || github.event.inputs.force_release == 'true'
      id: download
      run: |
        python .github/scripts/download_files.py
        
    - name: Create Release
      if: steps.monitor.outputs.changed == 'true' || github.event.inputs.force_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: ${{ steps.tag.outputs.name }}
        body: |
          检测到以下URL内容发生变化：
          
          ${{ steps.monitor.outputs.change_details }}
          
          变化详情：
          - URL 1: ${{ steps.monitor.outputs.url1_status }}
          - URL 2: ${{ steps.monitor.outputs.url2_status }}
          - URL 3: ${{ steps.monitor.outputs.url3_status }}
          
          下载的文件：
          ${{ steps.download.outputs.downloaded_files }}
          
          监控的URL：
          - ${{ env.URL_1 }}
          - ${{ env.URL_2 }}
          - ${{ env.URL_3 }}
          
          自动生成时间: ${{ steps.tag.outputs.timestamp }}
        draft: false
        prerelease: false
        files: |
          downloads/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}