name: URL Content Monitor and Release

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:
    inputs:
      force_release:
        description: '强制创建release'
        required: false
        default: 'false'
      check_all_urls:
        description: '检查所有URL（包括禁用的）'
        required: false
        default: 'false'

jobs:
  monitor-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Generate unique tag
      id: tag
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        TAG="release-${TIMESTAMP}-${GITHUB_RUN_ID}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo "name=自动发布-${TIMESTAMP}" >> $GITHUB_OUTPUT
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
        
    - name: Load URL configuration
      id: config
      run: |
        python .github/scripts/load_config.py
        
    - name: Download and compare content
      id: monitor
      env:
        CHECK_ALL_URLS: ${{ github.event.inputs.check_all_urls }}
      run: |
        python .github/scripts/url_monitor.py
        
    - name: Download changed files
      if: steps.monitor.outputs.changed == 'true' || github.event.inputs.force_release == 'true'
      id: download
      env:
        CHANGED_URLS: ${{ steps.monitor.outputs.changed_urls }}
      run: |
        python .github/scripts/download_files.py
        
    - name: Create Release
      if: steps.monitor.outputs.changed == 'true' || github.event.inputs.force_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: ${{ steps.tag.outputs.name }}
        body: |
          # 自动发布报告
          
          ## 变化摘要
          ${{ steps.monitor.outputs.change_details }}
          
          ## 监控详情
          ${{ steps.monitor.outputs.detailed_status }}
          
          ## 下载的文件
          **文件列表:** ${{ steps.download.outputs.downloaded_files_list }}
          
          **文件名:** ${{ steps.download.outputs.downloaded_filenames }}
          
          ## 统计信息
          - 总监控URL数量: ${{ steps.config.outputs.total_urls }}
          - 启用URL数量: ${{ steps.config.outputs.enabled_urls }}
          - 发生变化URL数量: ${{ steps.monitor.outputs.changed_count }}
          - 下载文件数量: ${{ steps.download.outputs.total_downloaded }}
          
          自动生成时间: ${{ steps.tag.outputs.timestamp }}
        draft: false
        prerelease: false
        files: |
          downloads/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}